- ci/no-std-check/Cargo.toml
- crates/ibc-types-core-client/Cargo.toml
- crates/ibc-types-lightclients-tendermint/Cargo.toml
- crates/ibc-types-timestamp/Cargo.toml
- crates/ibc-types/Cargo.toml
> `0.2.x`: plug back into upstream `ibc-proto`

- crates/ibc-types-core-channel/Cargo.toml
- crates/ibc-types-core-client/Cargo.toml
- crates/ibc-types-core-commitment/src/error.rs
- crates/ibc-types-core-connection/Cargo.toml
- crates/ibc-types-identifier/Cargo.toml
- crates/ibc-types-timestamp/Cargo.toml
- crates/ibc-types/Cargo.toml
- crates/ibc-types/src/lib.rs
Used the usual `cargo +nightly udeps --all-targets` to identify unused dependencies. Had to temporarily patch `crates/ibc-types/src/lib.rs` to remove the deny warnings directive, otherwise the command wouldn't succeed.
Closes #6.
> build: remove unused deps

- ci/no-std-check/Cargo.toml
- crates/ibc-types-core-channel/Cargo.toml
- crates/ibc-types-core-client/Cargo.toml
- crates/ibc-types-core-commitment/Cargo.toml
- crates/ibc-types-core-connection/Cargo.toml
- crates/ibc-types-domain-type/Cargo.toml
- crates/ibc-types-identifier/Cargo.toml
- crates/ibc-types-lightclients-tendermint/Cargo.toml
- crates/ibc-types-path/Cargo.toml
- crates/ibc-types-timestamp/Cargo.toml
- crates/ibc-types-transfer/Cargo.toml
- crates/ibc-types/Cargo.toml
This PR closes #39 : 
- bumps `tendermint-rs` to `0.33`
- bumps `ibc-proto` to `0.33`
- prepare release `v0.4.0`
> cargo: use `tendermint@0.33` and prepare `v0.4.0`

- crates/ibc-types-core-connection/Cargo.toml
- crates/ibc-types-core-connection/src/connection.rs
- release.sh
We should make sure that every crate is ready to be published. Otherwise, we might accidentally publish only a subset of all the crates in the workspace. This PR also adds a timer to avoid triggering the crates.io rate-limiter. Finally, this PR changes the `ibc-types-core-connection` serde feature to `with_serde` to fix trait resolution problems.
> ci: add dry-run phase and modify `with_serde` feature

- release.sh
Dry-runs are generally a good idea, but it's not possible here because our crates reference each other. Replacing the dry-run by running the `check_crates` script.
> ci(release): replace `dry-run` with `check_crates.sh`

- crates/ibc-types-core-channel/Cargo.toml
- crates/ibc-types-core-client/Cargo.toml
- crates/ibc-types-core-commitment/Cargo.toml
- crates/ibc-types-core-connection/Cargo.toml
- crates/ibc-types-domain-type/Cargo.toml
- crates/ibc-types-identifier/Cargo.toml
- crates/ibc-types-lightclients-tendermint/Cargo.toml
- crates/ibc-types-path/Cargo.toml
- crates/ibc-types-timestamp/Cargo.toml
- crates/ibc-types-transfer/Cargo.toml
- crates/ibc-types/Cargo.toml
This PR adds a `with_serde` feature to the root level crate that will activate `serde_derive`s in the subcrates. The reason is that the collision between `feature:serde` (which imports `serde`, `serde_derive` etc.) and `dep:serde` (imports the optional dependency `serde`) is causing problems with cargo when there are multiple levels of imports. To make matters more simple, we are creating a `with_serde` feature that activates everything serde related (`serde_json`, `serde_derive`, `erased-serde` etc.).
> ibc-types: prepare release `v0.6.0`

- crates/ibc-types-core-channel/Cargo.toml
- crates/ibc-types-core-channel/src/packet.rs
- crates/ibc-types-core-client/Cargo.toml
- crates/ibc-types-core-commitment/Cargo.toml
- crates/ibc-types-core-commitment/src/root.rs
- crates/ibc-types-core-connection/Cargo.toml
- crates/ibc-types-domain-type/Cargo.toml
- crates/ibc-types-identifier/Cargo.toml
- crates/ibc-types-lightclients-tendermint/Cargo.toml
- crates/ibc-types-path/Cargo.toml
- crates/ibc-types-timestamp/Cargo.toml
- crates/ibc-types-transfer/Cargo.toml
- crates/ibc-types/Cargo.toml
Minor improvements to how the `PacketData` and `MerkleRoot` structures are debug formatted #52
> ibc-types: prepare release `v0.6.1`

- docs/architecture/adr-006-upgrade-client-implementation.md
The `markdown-link-check` CI job was failing. Updated the in-repo URLs in the `docs/` folder to get it passing again. These changes are superficial: we may want to ditch those vestigial docs altogether, in favor of detailed rustdocs.
> docs: fix dead links

- crates/ibc-types-core-channel/Cargo.toml
- crates/ibc-types-core-client/Cargo.toml
- crates/ibc-types-core-commitment/Cargo.toml
- crates/ibc-types-core-connection/Cargo.toml
- crates/ibc-types-domain-type/Cargo.toml
- crates/ibc-types-identifier/Cargo.toml
- crates/ibc-types-lightclients-tendermint/Cargo.toml
- crates/ibc-types-path/Cargo.toml
- crates/ibc-types-timestamp/Cargo.toml
- crates/ibc-types-transfer/Cargo.toml
- crates/ibc-types/Cargo.toml
Includes docs changes from #63
> ibc-types: bump to 0.6.4

- ci/no-std-check/Cargo.toml
- crates/ibc-types-core-channel/Cargo.toml
- crates/ibc-types-core-client/Cargo.toml
- crates/ibc-types-core-client/src/error.rs
- crates/ibc-types-core-client/src/msgs/misbehaviour.rs
- crates/ibc-types-core-client/src/msgs/update_client.rs
- crates/ibc-types-core-commitment/Cargo.toml
- crates/ibc-types-core-connection/Cargo.toml
- crates/ibc-types-core-connection/src/msgs/conn_open_ack.rs
- crates/ibc-types-core-connection/src/msgs/conn_open_try.rs
- crates/ibc-types-domain-type/Cargo.toml
- crates/ibc-types-lightclients-tendermint/Cargo.toml
- crates/ibc-types-lightclients-tendermint/src/misbehaviour.rs
- crates/ibc-types-path/Cargo.toml
- crates/ibc-types-timestamp/Cargo.toml
This PR integrates the latest release of `tendermint-rs@0.34`, `ibc-proto-rs@0.37`, `ics23@0.11`, and switch prost to `0.12`. With this release, comes support for a new optional ics03 field which allows passing along proof objects of chains that cannot introspect their consensus state (https://github.com/cosmos/ibc/pull/839)
> ibc-types: switch to latest tendermint bindings and ics23 spec

- crates/ibc-types-core-channel/Cargo.toml
- crates/ibc-types-core-client/Cargo.toml
- crates/ibc-types-core-commitment/Cargo.toml
- crates/ibc-types-core-connection/Cargo.toml
- crates/ibc-types-domain-type/Cargo.toml
- crates/ibc-types-identifier/Cargo.toml
- crates/ibc-types-lightclients-tendermint/Cargo.toml
- crates/ibc-types-path/Cargo.toml
- crates/ibc-types-timestamp/Cargo.toml
- crates/ibc-types-transfer/Cargo.toml
- crates/ibc-types/Cargo.toml
This PR prepares a new breaking release of the `ibc-types` crates. It should be rebased onto `main` when #66 lands.
> ibc-types: prepare release `v0.7.0`

- crates/ibc-types-core-client/Cargo.toml
- crates/ibc-types-core-client/src/height.rs
Needed to Ics20Withdraw can be deserialized in the Penumbra wasm crate
> Add deserialization for height

- crates/ibc-types-core-client/src/mock/client_state.rs
- crates/ibc-types-lightclients-tendermint/src/client_state.rs
Necessary to implement IBC unfreeze chain proposals in penumbra-zone/penumbra
> ibc-types-core-client(mock): Support unfreezing an IBC client

- crates/ibc-types-core-channel/Cargo.toml
- crates/ibc-types-core-client/Cargo.toml
- crates/ibc-types-core-commitment/Cargo.toml
- crates/ibc-types-core-connection/Cargo.toml
- crates/ibc-types-domain-type/Cargo.toml
- crates/ibc-types-identifier/Cargo.toml
- crates/ibc-types-lightclients-tendermint/Cargo.toml
- crates/ibc-types-path/Cargo.toml
- crates/ibc-types-timestamp/Cargo.toml
- crates/ibc-types-transfer/Cargo.toml
- crates/ibc-types/Cargo.toml
This release includes the `ibc-proto@0.39` integration, which notably uses a non-object safe `Protobuf` trait re-exported from `tendermint-proto`.
> ibc-types: prepare release `0.9.0`

- crates/ibc-types-core-channel/Cargo.toml
- crates/ibc-types-core-client/Cargo.toml
- crates/ibc-types-core-commitment/Cargo.toml
- crates/ibc-types-core-connection/Cargo.toml
- crates/ibc-types-domain-type/Cargo.toml
- crates/ibc-types-identifier/Cargo.toml
- crates/ibc-types-lightclients-tendermint/Cargo.toml
- crates/ibc-types-path/Cargo.toml
- crates/ibc-types-timestamp/Cargo.toml
- crates/ibc-types-transfer/Cargo.toml
- crates/ibc-types/Cargo.toml
This release removes the `TypeUrl` trait and replaces it with the new `prost::Name` impl that is part of `ibc-proto@0.39.1`
> ibc-types: prepare release `v0.10.0`

- ci/no-std-check/Cargo.toml
- crates/ibc-types-core-channel/Cargo.toml
- crates/ibc-types-core-client/Cargo.toml
- crates/ibc-types-core-commitment/Cargo.toml
- crates/ibc-types-core-connection/Cargo.toml
- crates/ibc-types-domain-type/Cargo.toml
- crates/ibc-types-identifier/Cargo.toml
- crates/ibc-types-lightclients-tendermint/Cargo.toml
- crates/ibc-types-path/Cargo.toml
- crates/ibc-types-timestamp/Cargo.toml
- crates/ibc-types-transfer/Cargo.toml
- crates/ibc-types/Cargo.toml
Updating ibc-proto-rs to be our fork until we have official protojson support: https://github.com/cosmos/ibc-proto-rs/pull/166
Also bumped version to v0.11.0
> ibc-types: use `ibc-proto-rs` fork and prepare release `0.11`

- ci/no-std-check/Cargo.toml
- crates/ibc-types-core-channel/Cargo.toml
- crates/ibc-types-core-client/Cargo.toml
- crates/ibc-types-core-commitment/Cargo.toml
- crates/ibc-types-core-connection/Cargo.toml
- crates/ibc-types-domain-type/Cargo.toml
- crates/ibc-types-identifier/Cargo.toml
- crates/ibc-types-lightclients-tendermint/Cargo.toml
- crates/ibc-types-path/Cargo.toml
- crates/ibc-types-timestamp/Cargo.toml
- crates/ibc-types-transfer/Cargo.toml
- crates/ibc-types/Cargo.toml
Reverts penumbra-zone/ibc-types#78
We should just wait for the upstream to be merged
> Revert "ibc-types: use `ibc-proto-rs` fork and prepare release `0.11`"

- ci/no-std-check/Cargo.toml
- crates/ibc-types-core-channel/Cargo.toml
- crates/ibc-types-core-client/Cargo.toml
- crates/ibc-types-core-commitment/Cargo.toml
- crates/ibc-types-core-connection/Cargo.toml
- crates/ibc-types-domain-type/Cargo.toml
- crates/ibc-types-identifier/Cargo.toml
- crates/ibc-types-lightclients-tendermint/Cargo.toml
- crates/ibc-types-path/Cargo.toml
- crates/ibc-types-timestamp/Cargo.toml
- crates/ibc-types-transfer/Cargo.toml
- crates/ibc-types/Cargo.toml
`ibc-proto-rs` now has proper protobuf json support in `v0.40.0`. This PR updates to the latest version to gain this functionality. Will fix serialization issues in the penumbra repo.
> Bump ibc-proto-rs + v0.11 release

- crates/ibc-types-core-channel/Cargo.toml
- crates/ibc-types-core-client/Cargo.toml
- crates/ibc-types-core-commitment/Cargo.toml
- crates/ibc-types-core-connection/Cargo.toml
- crates/ibc-types-domain-type/Cargo.toml
- crates/ibc-types-identifier/Cargo.toml
- crates/ibc-types-lightclients-tendermint/Cargo.toml
- crates/ibc-types-path/Cargo.toml
- crates/ibc-types-timestamp/Cargo.toml
- crates/ibc-types-transfer/Cargo.toml
- crates/ibc-types/Cargo.toml
The code we imported from the fork had an upper bound version specifier, which breaks downstream code's dependency resolution.
> Fix time dep

- crates/ibc-types-lightclients-tendermint/src/error.rs
- crates/ibc-types-lightclients-tendermint/src/header.rs
In the penumbra ibc-async implementation, this check is redundant (the state machine checks this), but since this is a stateless validation of a domain type it should exist in ibc-types.
> ibc-types-lightclients-tendermint: add more stateless validaton for validator set

- ci/no-std-check/Cargo.toml
- crates/ibc-types-core-channel/Cargo.toml
- crates/ibc-types-core-client/Cargo.toml
- crates/ibc-types-core-commitment/Cargo.toml
- crates/ibc-types-core-connection/Cargo.toml
- crates/ibc-types-domain-type/Cargo.toml
- crates/ibc-types-identifier/Cargo.toml
- crates/ibc-types-lightclients-tendermint/Cargo.toml
- crates/ibc-types-path/Cargo.toml
- crates/ibc-types-timestamp/Cargo.toml
- crates/ibc-types-transfer/Cargo.toml
- crates/ibc-types/Cargo.toml
In a followup it would be nice to switch over to use workspace dependencies.
> Update ibc-proto dependency to 0.41

- ci/no-std-check/Cargo.toml
- crates/ibc-types-core-channel/Cargo.toml
- crates/ibc-types-core-channel/src/channel.rs
- crates/ibc-types-core-channel/src/msgs/chan_close_confirm.rs
- crates/ibc-types-core-channel/src/msgs/chan_open_init.rs
- crates/ibc-types-core-channel/src/msgs/chan_open_try.rs
- crates/ibc-types-core-channel/src/msgs/timeout_on_close.rs
- crates/ibc-types-core-client/Cargo.toml
- crates/ibc-types-core-client/src/mock/client_state.rs
- crates/ibc-types-core-commitment/Cargo.toml
- crates/ibc-types-core-commitment/src/proof.rs
- crates/ibc-types-core-connection/Cargo.toml
- crates/ibc-types-domain-type/Cargo.toml
- crates/ibc-types-identifier/Cargo.toml
- crates/ibc-types-lightclients-tendermint/Cargo.toml
- crates/ibc-types-path/Cargo.toml
- crates/ibc-types-timestamp/Cargo.toml
- crates/ibc-types-transfer/Cargo.toml
- crates/ibc-types/Cargo.toml
This brings us in line with the latest changes from upstream Hermes.
> Update ibc-proto dependency to 0.42.0, prepare for 0.13.0 release

- crates/ibc-types-lightclients-tendermint/src/client_state.rs
- crates/ibc-types-lightclients-tendermint/src/error.rs
This PR adds a validation rule to the tendermint `ClientState` struct to forbid empty chain ids.
> zellic audit remediations

- crates/ibc-types-core-channel/Cargo.toml
- crates/ibc-types-core-client/Cargo.toml
- crates/ibc-types-core-commitment/Cargo.toml
- crates/ibc-types-core-connection/Cargo.toml
- crates/ibc-types-domain-type/Cargo.toml
- crates/ibc-types-identifier/Cargo.toml
- crates/ibc-types-lightclients-tendermint/Cargo.toml
- crates/ibc-types-path/Cargo.toml
- crates/ibc-types-timestamp/Cargo.toml
- crates/ibc-types-transfer/Cargo.toml
- crates/ibc-types/Cargo.toml
- flake.nix
This is to ship the breaking change in PR #88.
> chore: bump versions to 0.14.0

- crates/ibc-types-core-channel/Cargo.toml
- crates/ibc-types-core-channel/src/events/channel.rs
- crates/ibc-types-core-channel/src/events/packet.rs
- crates/ibc-types-core-channel/src/events/tests.rs
- crates/ibc-types-core-client/Cargo.toml
- crates/ibc-types-core-client/src/events.rs
- crates/ibc-types-core-commitment/Cargo.toml
- crates/ibc-types-core-connection/Cargo.toml
- crates/ibc-types-core-connection/src/events.rs
- crates/ibc-types-domain-type/Cargo.toml
- crates/ibc-types-identifier/Cargo.toml
- crates/ibc-types-lightclients-tendermint/Cargo.toml
- crates/ibc-types-lightclients-tendermint/src/client_state.rs
- crates/ibc-types-lightclients-tendermint/src/error.rs
- crates/ibc-types-path/Cargo.toml
- crates/ibc-types-timestamp/Cargo.toml
- crates/ibc-types-transfer/Cargo.toml
Updates the following dependencies:
+ ibc-proto: 0.42.2 -> 0.51.1
+ ics23: 0.11.3 -> 0.12.0
+ prost: 0.12.0 -> 0.13.3
+ tendermint: 0.34.0 -> 0.40.0
+ tendermint-light-client-verifier: 0.34.0 -> 0.40.0
+ tendermint-proto: 0.34.0 -> 0.40.0
+ tendermint-rpc: 0.34.0 -> 0.40.0
+ tendermint-testgen: 0.34.0 -> 0.40.0
The bump to the latest tendermint version required bumping prost, which in turns required updates of ibc-proto and ics23 (where I opted for their latest releases, respectively).
The two larger changes are:
1. From tendermint@v0.40.0 onward conversions between `core::time::Duration` and `protobuf.google.Duration` are now fallible. I introduced a newtype wrapper `CometBftDuration` to restore the previous behavior saturating at `i64::MAX` (for seconds) and `i32::MAX` (for nanos), …
> bump prost, tendermint, ibc-proto, ics23

- crates/ibc-types-core-channel/Cargo.toml
- crates/ibc-types-core-client/Cargo.toml
- crates/ibc-types-core-commitment/Cargo.toml
- crates/ibc-types-core-connection/Cargo.toml
- crates/ibc-types-domain-type/Cargo.toml
- crates/ibc-types-identifier/Cargo.toml
- crates/ibc-types-lightclients-tendermint/Cargo.toml
- crates/ibc-types-path/Cargo.toml
- crates/ibc-types-timestamp/Cargo.toml
- crates/ibc-types-transfer/Cargo.toml
- crates/ibc-types/Cargo.toml
This prepare release `v0.15.0` of ibc-types.
> ibc-types: bump to `v0.15.0`

- crates/ibc-types-core-channel/Cargo.toml
- crates/ibc-types-core-client/Cargo.toml
- crates/ibc-types-core-commitment/Cargo.toml
- crates/ibc-types-core-connection/Cargo.toml
- crates/ibc-types-lightclients-tendermint/Cargo.toml
- crates/ibc-types-path/Cargo.toml
- crates/ibc-types/Cargo.toml
This patch bumps the recently released `ibc-proto@v0.52.0` and prepares a new release of all crates that have it as a direct or transient dependency:
+ ibc-types@v0.16.0
+ ibc-types-core-channel@v0.16.0
+ ibc-types-core-client@v0.16.0
+ ibc-types-core-commitment@v0.16.0
+ ibc-types-core-connection@v0.16.0
+ ibc-types-lightclients-tendermint@v0.16.0
+ ibc-types-path@v0.16.0
Because ibc-proto now has a msrv of rust 1.75.0 because of its dependency on tonic, I have set `rust-version = "1.75.0"` in all the aforementioned crates.
Note that this patch currently breaks with the convention of bumping all crate versions in the workspace in lock-step: some of the crates are not affected by the changes and so I have opted to not change them. If it is desired to have a lockstep release I can also do …
> bump ibc-proto@v0.52.0, ibc-types@v0.16
